name: Build app

on:
  push:
    branches: master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, mingw32, mingw64]

    name: Create build
    runs-on: ubuntu-latest

    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependency
        run: sudo apt install -y libxft-dev

      - name: Add required dependency for Windows build
        if: ${{ matrix.platform != 'linux' }}
        run: sudo apt install -y mingw-w64

      - name: Prepare FLTK
        run: |
          wget https://www.fltk.org/pub/fltk/1.3.7/fltk-1.3.7-source.tar.gz
          tar -xzf fltk-1.3.7-source.tar.gz

      - name: Build FLTK
        run: make fltklib

      - name: Build app
        run: make

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-executable
          path: |
            joeclient
            joeclient.exe
